### ISSUE TITLE
cannot import name 'is_image_file'

### ISSUE THREAD

**Issue by AmosLewis** [inferno-pytorch/inferno#104]
* inferno version:v0.1.7
* Python version:3.6
* Operating System:ubuntu16

### Description
I try to use inferno trainers, come with the output:
cannot import name 'is_image_file'

### What I Did

```
$ python alderley_patchcwganp.py 
Traceback (most recent call last):
  File "alderley_patchcwganp.py", line 9, in <module>
    from inferno.trainers.basic import Trainer
  File "/home/jiangsht/anaconda2/envs/chi/inferno/__init__.py", line 6, in <module>
    from . import io
  File "/home/jiangsht/anaconda2/envs/chi/inferno/io/__init__.py", line 1, in <module>
    from . import box
  File "/home/jiangsht/anaconda2/envs/chi/inferno/io/box/__init__.py", line 3, in <module>
    from .camvid import CamVid, get_camvid_loaders
  File "/home/jiangsht/anaconda2/envs/chi/inferno/io/box/camvid.py", line 9, in <module>
    from torchvision.datasets.folder import is_image_file, default_loader
ImportError: cannot import name 'is_image_file'


```

**Comment by constantinpape** [comment]
This is an issue with newer torchvision releases.
We will work on fixing this.

In the meantime, you can avoid this error by using an older torchvision release.
I know for certain that 0.17 works, not sure about the following releases.

**Comment by bstriner** [comment]
There are some other problems with latest pytorch, but PR for this specific issue here: https://github.com/inferno-pytorch/inferno/pull/106

**Comment by constantinpape** [comment]
@bstriner s PR is merged and this issue should be fixed.
